resources:
- name: anniversaries-api
  type: git
  source:
    uri: https://github.com/bu3/anniversaries-api
    branch: master

- name: cloud-foundry
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: Catulla
    space: development

jobs:
- name: test
  plan:
  - get: anniversaries-api
    trigger: true
  - task: tests
    file: anniversaries-api/ci/tasks/test.yml
  - put: cloud-foundry
    params:
      manifest: ./artifact/manifest.yml
